Traceroute Map Population
TheSirLancelot/Netulla pull request #38
Opened 2023-10-28 23:23 UTC by nevermore23274

- Changed dockerfile to use 3.11.6-slim-bookworm as it's a smaller image
- Updated streamlit from 1.27 to 1.28 (see https://docs.streamlit.io/library/changelog )
- Added geopy and ip2geotools
- Added new program mtr
- Added an apt cache clean to help reduce image size
- Added two environment variables to: 1.) Ensure localhost is used 2.) Stop browser from sending usage stats
- Implemented a calculated zoom function for the window after IP/DNS scan
- Added checkbox for raw mtr output
- Added slider for scatter point radius
- Added functions to rescan if the checkbox or slider are adjusted after a scan
- Added function to clean up the MTR output so the data matches the columns
- Made some changes to other files to fix pylint gripes

Closes #5

2023-10-30 15:32 UTC, TheSirLancelot requested changes

2023-10-30 15:32 UTC, TheSirLancelot commented on functions/n1_Network_Tool.py
> +    import streamlit as st
I don't think the intended benefit of importing within our functions is worth it in our case. I'm fine voting whether we keep this pylint rule or not, but in my opinion, it's usually better to err on the side of the style guide(s).

2023-10-30 15:32 UTC, TheSirLancelot commented on functions/n1_Network_Tool.py
> +                    hops = re.findall(r"\d+\.\|\-\- ([\d\.]+|[\?\?\?]+)", output)
mtr has a --json option.. Might make your life a lot easier: https://manpages.debian.org/testing/mtr/mtr.8.en.html#j

2023-10-30 15:32 UTC, TheSirLancelot commented on functions/n1_Network_Tool.py
Code looks good from initial review. Take a look at my comments and let me know if you want to take action on them.

2023-10-30 17:35 UTC, nevermore23274 commented on functions/n1_Network_Tool.py
> +    import streamlit as st
On this, my intent was to simply get the code working and pushed. However, once everyone has finished their phase one stuff, I want to go through and all of the imports that are used in more than one function (such as streamlit) will just be imported at the top of the code base. The rest of the imports that are only used in one function can be called within the function so that, for instance, you opening up the network tool page doesn't load ALL the libraries. As we add more functions, this may become something of worthy note.

2023-10-30 17:37 UTC, nevermore23274 commented on functions/n1_Network_Tool.py
> +                    hops = re.findall(r"\d+\.\|\-\- ([\d\.]+|[\?\?\?]+)", output)
The main reason I chose to use regex is due to the fact that I'm not having to call any specialized terminal commands within our code base, as it's a bit more of a process to troubleshoot when it's being shot out in the terminal vs me being able to see it on the actual webpage and just use regex to process the data.
However, I can switch to the --json if that's the preference.

2023-10-30 18:49 UTC, TheSirLancelot commented on functions/n1_Network_Tool.py
> +    import streamlit as st
Ok, I'm fine with that. I'll make an issue to fix the pylint issues we're ignoring and add this one to it.

2023-10-30 18:50 UTC, TheSirLancelot commented on functions/n1_Network_Tool.py
> +                    hops = re.findall(r"\d+\.\|\-\- ([\d\.]+|[\?\?\?]+)", output)
Aren't you already calling the mtr command in the terminal and just passing the output to the webpage?

2023-10-31 03:58 UTC, nevermore23274 commented on functions/n1_Network_Tool.py
> +                    hops = re.findall(r"\d+\.\|\-\- ([\d\.]+|[\?\?\?]+)", output)
I am. But I made the regex prior to using MTR (was still trying to just use traceroute) and it happened to carry over nicely. Didn't see a reason to overcomplicate if using regex vs --json would essentially give the same thing. If we have time to start optimizing our code base, or decide we want to add more functionality to the tool, then that may be something worth exploring.

But as of this moment, I don't feel using one option over the other makes a difference, especially not if regex is already doing the intended task.

2023-10-31 04:16 UTC, TheSirLancelot commented on functions/n1_Network_Tool.py
> +                    hops = re.findall(r"\d+\.\|\-\- ([\d\.]+|[\?\?\?]+)", output)
Sounds good to me. Thanks for the explanation!

2023-10-31 04:17 UTC, TheSirLancelot approved these changes

2023-10-31 04:18 UTC, TheSirLancelot approved these changes

2023-10-31 04:27 UTC, merged