20 web based wget or curl
TheSirLancelot/Netulla pull request #62
Opened 2023-11-21 06:08 UTC by Tymaze3

created WGET tool, created unit test for certificate lookup. It is saying I can't automatically merge

2023-11-21 18:51 UTC, tyoung-99 reviewed
I think you used the wrong branch for this. Your branch and issue are for the WGET tool, but these are your tests for the certificate lookup tool. You should be able to change the branch name/PR name and unlink the incorrect issue.

2023-11-21 18:51 UTC, tyoung-99 commented on tests/test_frontend.py
> +    page.get_by_text("Network Analysis").click()
This should be "Network Tool" not "Network Analysis." It's causing your tests to fail currently. Don't forget you can run the tests locally beforehand to resolve any issues before your PR.

2023-11-21 19:00 UTC, tyoung-99 commented
I see the problem. Your second commit deleted the WGET and HTTP header tools. The HTTP header tool was reobtained with the later merge of dev into your branch, but obviously your WGET tool wasn't, since it wasn't in dev yet. You'll just need to get that back.

2023-11-27 02:43 UTC, TheSirLancelot requested changes

2023-11-27 02:43 UTC, TheSirLancelot commented on Pipfile
I assume this file has something to do with your local dev environment. Should add this to the .gitignore

2023-11-27 02:43 UTC, TheSirLancelot commented on index.html
Not sure how this got added to your directory either, but needs to be deleted..

2023-11-27 02:43 UTC, TheSirLancelot commented on tests/.DS_Store
I assume this file has something to do with your local dev environment. Should add this to the .gitignore

2023-11-27 02:43 UTC, TheSirLancelot commented on tests/test_frontend.py
> +        running_icon.wait_for(state="hidden")
According to @tyoung-99 this is not a good way of waiting for results. It would be better to wait for your table of results to be visible.

2023-11-27 02:43 UTC, TheSirLancelot commented on tests/test_frontend.py
> +    page.get_by_role("img", name="open").click()
See @tyoung-99 comments about using the new way to navigate to your tools.

2023-11-27 02:43 UTC, TheSirLancelot commented on tests/test_frontend.py
> +    enter_domain("timeout.com")
This is a valid domain, it's not going to timeout

2023-11-27 02:43 UTC, TheSirLancelot commented on tests/test_frontend.py
> +    page.get_by_label("Enter a URL (e.g., google.com)").click()
You should use your `enter_domain()` function for this to maintain uniformity

2023-11-28 04:42 UTC, Tymaze3 commented on tests/test_frontend.py
> +    page.get_by_label("Enter a URL (e.g., google.com)").click()
So just replace page.get_by_label to enter_domain()

2023-11-28 04:43 UTC, TheSirLancelot commented on tests/test_frontend.py
> +    page.get_by_label("Enter a URL (e.g., google.com)").click()
Yea that was using the same logic as the enter_domain function anyways. Just redundant

2023-11-28 04:43 UTC, Tymaze3 commented on tests/test_frontend.py
> +        running_icon.wait_for(state="hidden")
So just remove  running_icon.wait_for

2023-11-28 04:46 UTC, Tymaze3 commented on tests/test_frontend.py
> +    page.get_by_role("img", name="open").click()
Got it!

2023-11-28 04:49 UTC, TheSirLancelot commented on tests/test_frontend.py
> +        running_icon.wait_for(state="hidden")
Take a look at some of the other tests (whois, ns lookup, etc) and see what they're waiting on. It's just the subheading or whatever that your results are populated under. If you wait for that, you'll know that _something_ is getting displayed by your feature. Make sense?

2023-11-28 08:21 UTC, tyoung-99 submitted a review, later dismissed

2023-11-28 08:21 UTC, tyoung-99 commented on tests/test_frontend.py
> +        page.get_by_label("Enter a URL (e.g., google.com)").press("Enter")
This doesn't do anything when you have a button to press. You need to press the button instead. See my HTTP header tool test for how to do that.

2023-11-28 08:21 UTC, tyoung-99 commented on tests/test_frontend.py
> +    expect(error).to_have_text("Please enter a valid domain.")
There are a number of errors in the text you're expecting, including this one. Double check each one on your tool to see what message is supposed to be displayed. If what's here is what's supposed to be displayed, you'll need to update your tool to display that message instead.

2023-11-28 19:50 UTC, TheSirLancelot requested changes

2023-11-28 19:50 UTC, TheSirLancelot commented on Pipfile
This never got added to the .gitignore. Is it needed for your dev environment?

2023-11-28 19:50 UTC, TheSirLancelot commented on index.html
This never got added to the .gitignore. Is it needed for your dev environment?

2023-11-28 19:50 UTC, TheSirLancelot commented on tests/.DS_Store
This never got added to the .gitignore. Is it needed for your dev environment?

2023-11-28 19:50 UTC, TheSirLancelot commented on tests/test_frontend.py
You're not actually testing that you get successful output on a known-good domain (www.google.com). I will make the edit for the sake of time. Make sure you check it out so you know what I changed.

2023-11-28 19:50 UTC, TheSirLancelot commented on functions/n1_Network_Tool.py
> +def online_wget_tool():
This function doesn't appear to be working. We really should have split this and the certificate test into two separate pull requests, because now this is going to hold up those tests getting into dev.

![image](https://github.com/TheSirLancelot/Netulla/assets/22830818/3823c32a-b71a-4298-8e82-138231828f06)

2023-11-28 19:59 UTC, TheSirLancelot commented on functions/n1_Network_Tool.py
> +def online_wget_tool():
Once I manually install `wget` in the docker image, the function works fine:

![image](https://github.com/TheSirLancelot/Netulla/assets/22830818/2668c94d-56fd-4df3-963a-3fee014b61c7)

Recommend modifying line 4 in the dockerfile to the following:
`RUN apt-get update && apt-get install -y nmap mtr wget`

2023-11-28 20:00 UTC, TheSirLancelot commented on functions/n1_Network_Tool.py
> +def online_wget_tool():
Also, I recommend moving the `Sample URL: https://www.example.com` into the URL box to begin with so it doesn't show when you display the results

2023-11-28 22:45 UTC, Tymaze3 commented on functions/n1_Network_Tool.py
> +def online_wget_tool():
I added curl to the dockerfile, and added online_curl_tool to page1_funcs.

2023-11-29 02:48 UTC, TheSirLancelot approved these changes

2023-11-29 03:12 UTC, tyoung-99 approved these changes
I don't know that it's something we can fix, at least not easily, but unfortunately some sites give a nicely formatted response and others don't.
![image](https://github.com/TheSirLancelot/Netulla/assets/127442375/10ef0856-b1b5-436d-855d-773b92132f5a)
![image](https://github.com/TheSirLancelot/Netulla/assets/127442375/300242ed-2d1c-454a-bf99-62b20d0e241b)

Both sets of tests pass locally and online. The curl tool looks good. The only thing I'd like to see is a test for the two types of invalid URL in the curl tool, but that can be done separately for the sake of getting main updated now.

2023-11-29 03:14 UTC, TheSirLancelot commented
> I don't know that it's something we can fix, at least not easily, but unfortunately some sites give a nicely formatted response and others don't.
> 
> ![image](https://github.com/TheSirLancelot/Netulla/assets/127442375/10ef0856-b1b5-436d-855d-773b92132f5a)
> 
> ![image](https://github.com/TheSirLancelot/Netulla/assets/127442375/300242ed-2d1c-454a-bf99-62b20d0e241b)
> 
> 
> 
> Both sets of tests pass locally and online. The curl tool looks good. The only thing I'd like to see is a test for the two types of invalid URL in the curl tool, but that can be done separately for the sake of getting main updated now.

Yea I noticed that in my testing as well, I think that has to do with the site itself. Not sure there's much we can do there unfortunately.

2023-11-29 03:15 UTC, merged